simple-crud/routes/web.php
<?php

use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProductController;
use Faker\Guesser\Name;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('welcome');



require __DIR__ . '/auth.php';
Route::prefix('/admin')->middleware(['auth'])->group(function () {

    Route::get('/', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('/deleted-products', [ProductController::class, 'trash'])->name('product.trash');
    Route::get('/deleted-products/{id}/restore', [ProductController::class, 'restore'])->name('product.restore');
    Route::delete('/deleted-products/{id}', [ProductController::class, 'delete'])->name('product.delete');

    Route::resource('product', ProductController::class);
});

simple-crud/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable =['title','description','price','image','size'];
}

simple-crud/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

simple-crud/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

simple-crud/app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class FrontendController extends Controller
{
    public function index()
    {
       $products=Product::all();
       return view('welcome',compact('products'));

    }
}

simple-crud/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use Illuminate\Database\QueryException;
use Image;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {        
        $products=Product::all();
        return view('backend/products/index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend/products/add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreProductRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $requestData=$request->all();
        try {


            if ($request->hasFile('image')) {
                $file = $request->image;
                $path = "/app/public/products/";
                $filename = time() . '.' . $file->getClientOriginalExtension();
                Image::make($file)->resize(300, 200)->save(storage_path() . $path . $filename);
                $requestData['image'] = $filename;
            }

            Product::create($requestData);
            return redirect()->route('product.index')->with('message', 'product stored succesfully');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        
        return view('backend/products/view', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('backend/products/edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateProductRequest  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, Product $product)
    {
        try {
            $requestData = $request->all();

            // $product = Product::findOrFail($id);

            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $fileName = time() . '.' . $file->getClientOriginalExtension();
                Image::make($request->file('image'))
                    ->resize(300, 200)
                    ->save(storage_path() . '/app/public/products/' . $fileName);
                $requestData['image'] = $fileName;
            } else {
                $requestData['image'] = $product->image;
            }

            $product->update($requestData);

            return redirect()->route('product.index')->withMessage('Successfully Updated !');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('product.index')->withMessage('Successfully Deleted !');

    }
    public function trash()
    {
        $products = Product::onlyTrashed()->get();
        return view('backend.products.trash', compact('products'));
    }

    public function restore($id)
    {
        Product::withTrashed()
            ->where('id', $id)
            ->restore();

        return redirect()->route('product.trash')->withMessage('Successfully Restored !');
    }

    public function delete($id)
    {
        Product::withTrashed()
            ->where('id', $id)
            ->forceDelete();

        return redirect()->route('product.trash')->withMessage('Deleted Successfully');
    }








}

simple-crud/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

simple-crud/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

simple-crud/resources/views/backend/products/add.blade.php
<x-backend.layouts.master>

    <div class="container">
        <div class="row">
            <div class="card">

                <div class="card-body">
                    <div class="breadcrumb">
                        <li><a href="{{ route('product.index') }}">Products</a></li>/
                        <li> <a href="{{ route('product.create') }}">Add Products</a></li>/
                        <li><a href=""></a></li>
                    </div>
                </div>



            </div>

            <div class="card">
                <div class="card-title">
                    <legend class="text-center">Add Your Product</legend>
                </div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                    @endif
                                    
                    

                    <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <!-- 2 column grid layout with text inputs for the first and last names -->
                        <div class="row">
                            <div class="col">
                                <div class="form-outline">
                                    <input type="text" id="form6Example1" class="form-control" name="title"
                                        value="{{ old('title') }}" />
                                    <label class="form-label" for="form6Example1">Product title</label>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-outline">
                                    <input type="number" id="form6Example5" class="form-control" name="price"
                                        value="{{ old('price') }}" />
                                    <label class="form-label" for="form6Example5">Price</label>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-outline">
                                    <select name="size" id="size" class="form-control">
                                        <option value="M">M</option>
                                        <option value="S">S</option>
                                        <option value="L">L</option>
                                        <option value="XL">XL</option>
                                    </select>
                                    <label class="form-label" for="size">size</label>
                                </div>
                            </div>
                        </div>

                        <!-- Text input -->


                        <!-- Text input -->



                        <!-- Number input -->


                        <!-- Message input -->
                        <div class="form-outline">
                            <textarea class="form-control" id="mytextarea" name="description" rows="4">{{ old('description') }}</textarea>
                            <label class="form-label" for="mytextarea">Description</label>
                        </div>

                        <!-- Checkbox -->
                        <div class="form-outline">
                            <label class="form-label" for="customFile">Select a image:</label>
                            <input type="file" class="form-control" id="customFile" name="image"
                                value="{{ old('image') }}" />
                        </div>

                        <!-- Submit button -->
                        <button type="submit" class="mt-2 btn btn-primary w-100">Upload Product</button>


                    </form>





                </div>
            </div>
        </div>






    </div>














</x-backend.layouts.master>

simple-crud/resources/views/backend/products/edit.blade.php
<x-backend.layouts.master>

    <div class="container">
        <div class="row">
            <div class="card">

                <div class="card-body">
                    <div class="breadcrumb">
                        <li><a href="{{ route('product.index') }}">Products</a></li>/
                        <li> Edit</li>/
                        <li><a href=""></a></li>
                    </div>
                </div>

            </div>

            <div class="card">
                <div class="card-title">
                    <legend class="text-center">Edit Product</legend>
                </div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                    @endif                                                        
                    <form action="{{ route('product.update',$product->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('patch')
                        <!-- 2 column grid layout with text inputs for the first and last names -->
                        <div class="row">
                            <div class="col">
                                <div class="form-outline">
                                    <input type="text" id="form6Example1" class="form-control" name="title"
                                        value="{{ old('title',$product->title) }}" />
                                    <label class="form-label" for="form6Example1">Product title</label>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-outline">
                                    <input type="number" id="form6Example5" class="form-control" name="price"
                                        value="{{ old('price', $product->price) }}" />
                                    <label class="form-label" for="form6Example5">Price</label>
                                </div>
                            </div>
                        </div>

                        <!-- Text input -->


                        <!-- Text input -->



                        <!-- Number input -->


                        <!-- Message input -->
                        <div class="form-outline">
                            <textarea class="form-control" id="mytextarea" name="description" rows="4">{{ old('description',$product->description) }}</textarea>
                            <label class="form-label" for="mytextarea">Description</label>
                        </div>

                        <!-- Checkbox -->
                        <div class="form-outline row">
                           
                            <div class="col">
                                Old image
                                <img src="{{asset('storage/products/'.$product->image)}}" alt="">
                            </div>
                            <div class="col"><label class="form-label" for="customFile">Select a image:</label>
                                <input type="file" class="form-control" id="customFile" name="image"
                                    value="{{ old('image') }}" /></div>
                        </div>

                        <!-- Submit button -->
                        <button type="submit" class="mt-2 btn btn-primary w-100">Update Product</button>


                    </form>





                </div>
            </div>
        </div>






    </div>














</x-backend.layouts.master>

simple-crud/resources/views/backend/products/index.blade.php
<x-backend.layouts.master>

    <div class="container">
        <div class="row">
            <div class="card"> 
                <div class="d-flex justify-content-between">
                    <div class="breadcrumb">
                        <li><a href="{{ route('product.index') }}">Products</a></li>/

                        <li><a href=""></a></li>
                    </div>

                    <div>
                        {{-- <a href="{{route('product.trash')}}" class="btn btn-outline-secondary">Trash bin</a> --}}
                        <a href="{{ route('product.create') }}" class="btn btn-outline-info">Add a product</a>
                    </div>
                </div>

            </div>

            <div class="card">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{ session()->get('message') }}
                    </div>
                @endif

                <table>
                    <thead>
                        <th>#</th>
                        <th>photo</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Size</th>
                        <th>Price</th>
                        <th>Action</th>
                    </thead>
                    <tbody>
                        @foreach ($products as $product)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td><img src="{{ asset('storage/products/' . $product->image) }}" alt="No image"
                                        style="max-width: 40px; max-height:40px;"></td>
                                <td>{{ $product->title }}</td>
                                <td>{{ Str::limit($product->description, 20) }}</td>
                                <td>{{ $product->size }}</td>
                                <td>{{ $product->price }}</td>
                                <th>
                                    <div class="d-flex">
                                        <a href="{{route('product.show',$product->id)}}" class="btn btn-primary btn-sm">View</a>
                                        <a href="{{route('product.edit',$product->id)}}" class="btn btn-warning btn-sm">Edit</a>
                                        <form action="{{route('product.destroy',$product->id)}}" method="POST">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-danger btn-sm">Delete</button>
                                        </form>
                                    </div>
                                </th>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>






    </div>














</x-backend.layouts.master>

simple-crud/resources/views/backend/products/trash.blade.php
<x-backend.layouts.master>

    <div class="container"> 
        <a href="{{route('product.index')}}" class="btn btn-primary">Go back</a>
        <div class="row">
            <h1>Trash list</h1>

            <div class="card">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{ session()->get('message') }}
                    </div>
                @endif
                <table>
                    <thead>
                        <th>#</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Action</th>
                    </thead>
                    <tbody>
                        @foreach ($products as $product)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $product->title }}</td>
                                <td>{{ Str::limit($product->description, 20) }}</td>
                                <td>{{ $product->price }}</td>
                                <th>
                                    <div class="d-flex">
                                        <a href="{{route('product.restore',$product->id)}}" class="btn btn-primary btn-sm">restore</a>
                                        <form action="{{route('product.delete',$product->id)}}" method="POST">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-danger btn-sm">Delete</button>
                                        </form>
                                    </div>
                                </th>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>






    </div>














</x-backend.layouts.master>

simple-crud/resources/views/backend/products/view.blade.php
<x-backend.layouts.master>
    <div class="container">
        <div class="card">

            <div class="card-body">
                <div class="breadcrumb">
                    <li><a href="{{ route('product.index') }}">Products</a></li>/
                    <li>{{$product->title}}</li>
                </div>
            </div>



        </div>

          
            <div class="card" style="max-width: 350px" >
                <div class="text-center">
                    <img src="{{asset('storage/products/'.$product->image)}}" class="img-fluid rounded" style="width:fit-content;" alt="No image">
                </div>
                <div class="card-title text-center">
                    {{$product->title}}
                    <hr>
                </div>
                <div class="card-body">

                    <div class="card-group row w-100">
                        <div class="card-column">
                            <p>{{$product->description}}</p>
                        </div>
                        <div class="col">
                            Price: {{$product->price}} <br>
                         Size: <mark>  {{$product->size}} </mark> 
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="d-flex"><a href="{{route('product.index')}}" role="button" class="btn btn-outline-success w-50" >Back</a>
                        <a href="{{route('product.edit',$product->id)}}"  class="btn btn-outline-info w-50">Edit</a></div>
                    
                    <form action="" method="POST">
                        @csrf
                        @method('delete')
                        <button class="btn btn-outline-danger w-100">Delete</button>
                    </form>
                </div>
            </div>
       
    </div>
</x-backend.layouts.master>

simple-crud/resources/views/dashboard.blade.php
<x-backend.layouts.master>
<h1>Wellcome to dashboard</h1>
  
<div class="card">


    <div class="card-body">
        <a href="{{route('product.index')}}">Products</a>
    </div>
</div>



</x-backend.layouts.master>

simple-crud/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

simple-crud/resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

simple-crud/resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>